# Generated by Django 4.0.5 on 2022-06-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('CREATED', 'created'), ('PENDING', 'pending'), ('APPROVED', 'approved')], db_index=True, default='created', max_length=10),
        ),
    ]
