# Generated by Django 4.0.5 on 2022-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.AlterField(
            model_name='user',
            name='employer',
            field=models.CharField(max_length=150, null=True, verbose_name='employer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=150, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
    ]
