# Generated by Django 4.0.5 on 2022-06-27 03:12

from django.db import migrations, models
import metadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('expertise', 'Expertise'), ('membership_area', 'Membership Area')], db_index=True, max_length=25, verbose_name='Key to Metadata')),
                ('value', models.CharField(max_length=255, verbose_name='Value to Metadata')),
            ],
            options={
                'db_table': 'metadatas',
            },
            managers=[
                ('objects', metadata.models.MetadataManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.CheckConstraint(check=models.Q(('key__in', ['expertise', 'membership_area'])), name='valid_key'),
        ),
    ]
